package com.swp.project.entity.user;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.*;

import java.time.Instant;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class PendingRegister {
    @Id
    private String email;

    private String passwordHash;

    private String autoGeneratedOtp;

    private Instant otpExpiryTime;
}
