package com.swp.project.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.*;

import java.time.Instant;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
public class PendingRegister {
    @Id
    private String email;

    @Column(nullable = false)
    private String passwordHash;

    @Column(nullable = false)
    private String autoGeneratedOtp;

    @Column(nullable = false)
    private Instant otpExpiryTime;
}
